# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy currensee backend
        uses: appleboy/ssh-action@v0.1.2
        with: 
          host: ${{ secrets.SSH_HOST }} #IP of the server you wish to SSH into
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          
          script: | 
            mkdir test #create folder you want to deploy in to the live server
            cd test
            git clone git@github.com:jbrennan414/currensee_backend.git
            echo 'Deployment was successful to Digital Ocean
            
